// <auto-generated />
namespace VladPC.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class replace_sum_to_price_and_count : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replace_sum_to_price_and_count));
        
        string IMigrationMetadata.Id
        {
            get { return "202311201527104_replace_sum_to_price_and_count"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
