// <auto-generated />
namespace VladPC.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_nameProcurement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_nameProcurement));
        
        string IMigrationMetadata.Id
        {
            get { return "202311201531208_add_nameProcurement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
